language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
    - composer selfupdate
    - composer install --dev --prefer-source

script:
    - phpunit --colors --coverage-text
    - bin/heydoc --version
    - bin/heydoc list
    - bin/heydoc setup
    - bin/heydoc check
    - bin/heydoc export
    - tree _export
    # - php composer.phar create-project heydoc/heydoc-application . --no-progress -s dev
